OpenFreeEnergy/IndustryBenchmarks2024

docs/source/public/contributing_inputs.rst

Change instructions to create fork first

---

docs/source/public/overview.rst

Add run instructions

---

docs/source/index.rst
docs/source/installation.rst

Add installation instructions

---

.github/pull_request_template.md
docs/source/public/contributing_inputs.rst
docs/source/public/input_preparation.rst
docs/source/public/overview.rst

Adding ligand prep instructions

---

docs/source/index.rst
docs/source/public/overview.rst

Fix TOC tree

---

docs/source/installation.rst

Update .yml file name in run instructions based on James feedback

---

docs/source/public/overview.rst

Change run instructions to run each input json three times

---

docs/source/index.rst
docs/source/public/overview.rst

Update front page [WIP]

---

docs/source/index.rst
docs/source/public/overview.rst

Cleaning up a few instructions:
First page:
Main public

Clean up a few things

---

docs/source/public/input_preparation.rst

Quick fix of a typo

---

docs/source/get-in-touch.rst
docs/source/installation.rst
docs/source/public/overview.rst

Improve various docs things

---

docs/source/installation.rst

fix conda-lock install typo

---

docs/source/public/input_preparation.rst

Add maestro instructions

---

docs/source/index.rst
docs/source/reviewersguide.rst

Add a reviewers guide

---

industry_benchmarks/utils/extras/extract_results.py

Fix file paths and runtype assignment

---

industry_benchmarks/utils/extras/extract_results.py

print traceback if simulation has errors

---

docs/source/public/overview.rst

Add documentation for handling failed simulations

---

industry_benchmarks/utils/extras/plot_results.py

Skip correlation statistics if bootstrapping fails

---

docs/source/public/overview.rst

see https://www.shellcheck.net/wiki/SC2086

add double quote to prevent globbing and word splitting

---

docs/source/public/overview.rst

fix typos and explain more how to find failed edges

---

docs/source/private/overview.rst
docs/source/public/overview.rst

Add documentation for the fix_network script

---

industry_benchmarks/utils/data_gathering.py
industry_benchmarks/utils/tests/test_data_gathering.py

Add tests for each function in the data gathering script.
#166 

`Data gathering`: function tests

---

docs/source/public/overview.rst

Docs: Fix bug in fix network description

---

docs/source/public/overview.rst

Update docs for the extract_results script

---

industry_benchmarks/utils/data_gathering.py
industry_benchmarks/utils/tests/test_data_gathering.py

Update the data gathering script to extract the MBAR free energy estimate and error. 

extract the MBAR error

---

industry_benchmarks/utils/data_gathering.py
industry_benchmarks/utils/tests/test_data_gathering.py

Add some atom pair fingerprints to the JSON to try and extract as much info as possible about the edges. 

Atom pair fingerprints

---

docs/source/public/overview.rst

Some text updates

---

docs/source/private/overview.rst
industry_benchmarks/utils/info_form_private_sets.txt

Info form for private datasets

---

README.md
docs/source/index.rst

Fixes #209 by pointing to the docs so we only have to update the info in one place.

Update readme and docs for current phase of benchmarking

---

docs/environment.yaml
docs/source/public/overview.rst

Updating the docs for submitting results

---

industry_benchmarks/analysis/1_download_and_extract_data.py

Use subsampling and calculate DG for each nanosecond of production simulation 

---

industry_benchmarks/analysis/README.md

Adds a table linking the analysis column names to a description.

Analysis metadata table 

---

docs/source/public/overview.rst

https://support.zenodo.org/help/en-gb/1-upload-deposit/74-can-i-upload-folders-directories
you can't upload a folder directly

Update upload steps

---

docs/source/public/overview.rst

ziped -> zipped

---

industry_benchmarks/analysis/2_pymbar4.py
industry_benchmarks/analysis/README.md
industry_benchmarks/analysis/pymbar4.yaml

Fixes #229 and adds a script to calculate the DG, bootstrap error and overlap matrix using pymbar4, note this is very slow using 1000 iterations which is currently hard coded. 

Add pymbar4 analysis script

---

industry_benchmarks/analysis/processed_results/get_statistics.py

Small fix in get_statistics script
